const fortuna = {
  0: "Tendrás un día de alegrías y buenos momentos, disfrútalos como nunca.",
  1: "Concéntrate en lo que quieres lograr y ganaras. No lo olvides.",
  2: "El cielo sera tu limite, pues grandes acontecimientos te sucederán.",
  3: "Te sentirás feliz como un niño y veras al mundo con sus ojos.",
  4: "Vivirás tu vejez con comodidades y riquezas materiales.",
  5: "Confía en tu suerte, que es mucha y te rodeara de prosperidad.",
  6: "No todo el mundo puede recibir las mismas cosas. Se practico.",
  7: "Te aguarda una larga y feliz vida.",
  8: "Hoy es el momento de explorar: no temas.",
  9: "Muy pronto seras incluido en muchas reuniones, fiestas y tertulias.",
  10: "Cuando busques lo que mas deseas, recuerda hacer tu mejor esfuerzo.",
  11: "Tienes por delante un maravilloso día para triunfar; disfrútalo y compártelo.",
  12: "Hoy seras reconocido por tus dones especiales y lograras ser feliz por muchas horas.",
  13: "Tu corazón estallara de alegría con la llegada de buenas noticias.",
  14: "Mañana puede ser muy tarde para disfrutar lo que tienes hoy.",
  15: "Seras promovido en tu trabajo debido a tus logros y capacidades.",
  16: "Alégrate, un camino de hermosas pasiones te espera y debes transitarlo",
  17: "Nunca tendrás que preocuparte por un ingreso estable.",
  18: "Hoy tendrás un día de increíble alegría y brillara tu sentido del humor.",
  19: "Hoy compartirás las horas mas tiernas de tu vida con alguien muy amado.",
  20: "La rueda de la fortuna te favorecerá y estarás rodeado de prosperidad.",
  21: "Tendrás entera satisfacción al final de esta temporada. Prepárate.",
  22: "Muchos se alegraran por tus logros y a ti te mejorara la vida.",
  23: "Eres una persona a la que le gusta triunfar en la vida.",
  25: "Confía en tu buen juicio y veras que este te lleva al triunfo.",
  26: "Se te cumplirá un hermoso sueño y veras como otros sueños se hacen realidad.",
  27: "No olvides que un amigo es un regalo que te das a ti mismo.",
  28: "Sabes que es exactamente lo que quieres. Trabaja en ello y hazlo materializarse.",
  29: "Siente la felicidad que espera por ti y no olvides atraparla para mantenerla contigo.",
};

module.exports = fortuna;
